Add services section
MRDriks/halcyon pull request #2
Opened 2020-09-17 18:10 UTC by MRDriks

2020-09-17 18:55 UTC, yanosh-almashi requested changes

2020-09-17 18:55 UTC, yanosh-almashi commented on src/sass/style.scss
> +%column-center-alignment {
what's the use of % character here?

2020-09-17 18:55 UTC, yanosh-almashi commented on src/sass/style.scss
> +    justify-content: center;
shouldn't this rule be added to %column-center-alignment class?

2020-09-17 18:55 UTC, yanosh-almashi commented on build/index.html
> +        <section class="section-services">
there is no need to name your section tag class as service-..., rename it to just "services"

2020-09-17 18:55 UTC, yanosh-almashi commented on build/index.html
> +            </div>
refactor classnames according to the comment above/

2020-09-18 07:10 UTC, MRDriks commented on src/sass/style.scss
> +%column-center-alignment {
In this block implemented template which allows inherit styles.

2020-09-18 07:59 UTC, closed without merging